### ISSUE TITLE
fragment data hg19 or hg38?

### ISSUE THREAD

**Issue by fl-yu** [Yang-Chen-Lab-co/COVID19-scATAC-seq#2]
Hi Thank you for sharing the data and code here!
I have a question about the data shared here. According to the description in the paper, all the data should be processed in the hg38 coordinates, while looking at the code in the repository, the fragment.tsv.gz seems generated with hg19. Maybe something I missed, is there any chance you could inform me if the data is hg19- or hg38- based?

**Comment by fl-yu** [comment]
Another request, could you help to upload the tbi file of 500_M4-fragments.tsv.gz? Thank you so much!!

**Comment by Yang-Chen-Lab-co** [comment]
> Hi Thank you for sharing the data and code here!
> I have a question about the data shared here. According to the description in the paper, all the data should be processed in the hg38 coordinates, while looking at the code in the repository, the fragment.tsv.gz seems generated with hg19. Maybe something I missed, is there any chance you could inform me if the data is hg19- or hg38- based?

Hey, the mini data shared here were generated with hg19, because hg19 is widely used. Actually, we have run both the hg19 and hg38 with the raw fastq data.

**Comment by Yang-Chen-Lab-co** [comment]
> Another request, could you help to upload the tbi file of 500_M4-fragments.tsv.gz? Thank you so much!!

Hey, You can delete the original tbi file, the ArchR would generate new tbi file.
