### ISSUE TITLE
some questions in figs3c

### ISSUE THREAD

**Issue by 1221li** [Yang-Chen-Lab-co/COVID19-scATAC-seq#3]
Dear author, I am very interested in your analysis. I have a small question to ask you. In the "MA" figure of Figs3C, if I use C11 as usegroup and C13 as bgdgroup, I can only export the peakList of C11, but not the PeakList of C13.  If I export the peakList with C13 as useGroup, the total quantity will change compared to the statement before conversion.  May I ask how you solved this problem?  Looking forward to your reply!  
<img width="596" alt="b8f6ed4f7dd51592a66444b3f70376a" src="https://user-images.githubusercontent.com/76415266/141708081-3b6a1502-6b7d-47d5-8c7c-f5fefdea779a.png">

**Comment by Yang-Chen-Lab-co** [comment]
> Dear author, I am very interested in your analysis. I have a small question to ask you. In the "MA" figure of Figs3C, if I use C11 as usegroup and C13 as bgdgroup, I can only export the peakList of C11, but not the PeakList of C13. If I export the peakList with C13 as useGroup, the total quantity will change compared to the statement before conversion. May I ask how you solved this problem? Looking forward to your reply!
> <img alt="b8f6ed4f7dd51592a66444b3f70376a" width="596" src="https://user-images.githubusercontent.com/76415266/141708081-3b6a1502-6b7d-47d5-8c7c-f5fefdea779a.png">

Hey, when run the getMarkerFeatures function, we set the C11 as useGroups, set the C13 as bgdGroups. Then run the getMarkers function which can export the marker peaks for C11 and C13.
